# Generated by Django 2.0.4 on 2019-03-13 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('fec_nacimiento', models.DateField()),
                ('nivel', models.CharField(max_length=50)),
                ('discapacidad', models.CharField(max_length=70)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SESION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.CharField(max_length=16)),
                ('fecha_fin', models.CharField(max_length=16)),
                ('area_visitada', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.CATEGORIA')),
                ('nn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.NN')),
            ],
        ),
    ]
