# Generated by Django 2.0.4 on 2019-03-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVIDAD_JUEGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.ACTIVIDAD')),
            ],
        ),
        migrations.CreateModel(
            name='CALIFICACION_JUEGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=70)),
                ('actividad_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.ACTIVIDAD_JUEGO')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.SESION')),
            ],
        ),
        migrations.CreateModel(
            name='ITEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('codigo', models.CharField(max_length=50)),
                ('actividad_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.ACTIVIDAD_JUEGO')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.CATEGORIA')),
            ],
        ),
        migrations.CreateModel(
            name='JUEGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='actividad_juego',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.JUEGO'),
        ),
    ]
