# Generated by Django 2.0.4 on 2019-03-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVIDAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('referencia', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='AREA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('referencia', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CALIFICACION_ORDEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ORDEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('codigo', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.ACTIVIDAD')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.CATEGORIA')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion_orden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.ORDEN'),
        ),
    ]
